// <auto-generated />
using System;
using AggregateVersions.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(OperationContext))]
    [Migration("20240827065822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Application", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c64fa529-34c0-431b-8e65-184c69c0f30c"),
                            Name = "CounterpartyApi",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("304b915e-d9ce-42a2-afa9-222f42a94f05"),
                            Name = "CounterpartyJob",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("f2d618ab-3f0b-408d-9455-ceb97a4076a1"),
                            Name = "CounterpartyWeb",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        });
                });

            modelBuilder.Entity("Core.Entities.DataBase", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("DataBases");

                    b.HasData(
                        new
                        {
                            ID = new Guid("1040744a-ad62-4db3-a449-ede765cecb7d"),
                            Name = "1-Counterparty",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("83d05b8d-69f6-485f-aa0e-ef447403b6aa"),
                            Name = "2-AccountManagement",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("d3de1b89-00c1-410e-aa25-7d17b5e5c40e"),
                            Name = "3-CCS_Oracle_views",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("400b30d8-3db4-4e5c-b989-b54489deec98"),
                            Name = "4-Common",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        });
                });

            modelBuilder.Entity("Core.Entities.Operation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3bbfff92-d6a3-4d7b-8c9f-5258bd88167b"),
                            Name = "Applications",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("b7ebb3de-cae7-4928-b372-c62cf42091e8"),
                            Name = "DataBases",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        },
                        new
                        {
                            ID = new Guid("8850acfe-e5d3-49b2-87b4-1d439ebcdb24"),
                            Name = "Reports",
                            ProjectID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46")
                        });
                });

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = new Guid("27af42de-1923-409d-91e4-3228a02f8f46"),
                            Name = "Counterparty"
                        },
                        new
                        {
                            ID = new Guid("a7dd8aa5-3c72-4f6b-a31b-4abbdfa096b4"),
                            Name = "Another"
                        });
                });

            modelBuilder.Entity("Core.Entities.Application", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("Applications")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Core.Entities.DataBase", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("DataBases")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Core.Entities.Operation", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("Operations")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("DataBases");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
